apiVersion: batch/v1
kind: Job
metadata:
  name: trivy-scan
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: scan
          image: ubuntu:18.04
          command: ['sh', '-c', '/bin/bash /script/script.sh']
          env:
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: access_key
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: secret_key
          - name: ENDPOINT_URL
            valueFrom:
              configMapKeyRef:
                name: minio-info
                key: endpoint_url
          - name: BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: minio-info
                key: bucket_name
          volumeMounts:
          - name: script
            mountPath: /script
      serviceAccountName: cluster-podlister
      restartPolicy: Never
      volumes:
        - name: script
          configMap:
            name: script-scan
            defaultMode: 0755
